$ErrorActionPreference = "Stop"

Write-Host "Запуск GymNet через Docker..."
Write-Host "1) Собрать и поднять контейнеры"
Write-Host "2) Открыть frontend в браузере"
Write-Host "3) Проверить backend health"
Write-Host "4) Проверить логи автозапуска ML-конвейера"
Write-Host "5) Опционально запустить профиль ML-ноутбука"
Write-Host "6) Опционально запустить GPU-конвейер ML"
Write-Host "7) Опционально запустить клиент веб-камеры"

Write-Host ""
Write-Host "Команды:"
Write-Host "powershell -ExecutionPolicy Bypass -File scripts/start_stack.ps1"
Write-Host "powershell -ExecutionPolicy Bypass -File scripts/start_stack.ps1 -NoBuild"
Write-Host "powershell -ExecutionPolicy Bypass -File scripts/start_stack.ps1 -NoML"
Write-Host "docker compose -f infra/docker-compose.yml up --build -d"
Write-Host "start http://localhost:8080"
Write-Host "start http://localhost:8000/api/health"
Write-Host "docker compose -f infra/docker-compose.yml logs ml-pipeline"
Write-Host "docker compose -f infra/docker-compose.yml --profile ml up --build -d ml-notebook"
Write-Host "docker compose -f infra/docker-compose.yml --profile ml run --rm ml-generate"
Write-Host "docker compose -f infra/docker-compose.yml --profile ml run --rm ml-train"
Write-Host "docker compose -f infra/docker-compose.yml --profile ml run --rm ml-eval"
Write-Host "docker compose -f infra/docker-compose.yml run --rm ml-pipeline"
Write-Host "docker compose -f infra/docker-compose.yml --profile ml-gpu run --rm ml-pipeline-gpu"
Write-Host "python scripts/collect_camera_dataset.py"
Write-Host "python scripts/camera_ws_client.py"
